### ISSUE TITLE
Updater broken

### ISSUE THREAD

**Issue by alex-mckinley** [Badaro/MTGODecklistCache#48]
I noticed that this hasn't been updated in a few days. I am not sure how automated it is, so I started running the updater app myself. When run, the updater app gives this error: 
```
NullReferenceException: Object reference not set to an instance of an object.
   at MTGODecklistCache.Updater.MtgMelee.Client.MtgMeleeClient.GetPlayers(Uri uri, Nullable`1 maxPlayers) in /mnt/c/Users/amcki/Documents/decklist_feed/MTGODecklistCache.Tools/MTGODecklistCache.Updater.MtgMelee.Client/MtgMeleeClient.cs:line 81
   at MTGODecklistCache.Updater.MtgMelee.Analyzer.MtgMeleeAnalyzer.GetScraperTournaments(MtgMeleeTournamentInfo tournament) in /mnt/c/Users/amcki/Documents/decklist_feed/MTGODecklistCache.Tools/MTGODecklistCache.Updater.MtgMelee.Analyzer/MtgMeleeAnalyzer.cs:line 24
   at MTGODecklistCache.Updater.MtgMelee.TournamentList.GetTournaments(DateTime startDate, Nullable`1 endDate) in /mnt/c/Users/amcki/Documents/decklist_feed/MTGODecklistCache.Tools/MTGODecklistCache.Updater.MtgMelee/TournamentList.cs:line 32
   at MTGODecklistCache.Updater.MtgMelee.MtgMeleeSource.GetTournaments(DateTime startDate, Nullable`1 endDate) in /mnt/c/Users/amcki/Documents/decklist_feed/MTGODecklistCache.Tools/MTGODecklistCache.Updater.MtgMelee/MtgMeleeSource .cs:line 22
   at MTGODecklistCache.Updater.App.Program.UpdateFolder[T](String cacheRootFolder, ITournamentSource`1 source, DateTime startDate, Nullable`1 endDate) in /mnt/c/Users/amcki/Documents/decklist_feed/MTGODecklistCache.Tools/MTGODecklistCache.Updater.App/Program.cs:line 53
   at MTGODecklistCache.Updater.App.Program.Main(String[] args) in /mnt/c/Users/amcki/Documents/decklist_feed/MTGODecklistCache.Tools/MTGODecklistCache.Updater.App/Program.cs:line 44
```

I wonder if this broke the automation of the update of this repo

**Comment by Badaro** [comment]
It's fully automated running once a day, but there may be something breaking. I'll check here and make a fix.

**Comment by Badaro** [comment]
@alex-mckinley Yes, it's breaking the automation, since this causes an error the process stops before pushing+commiting. I've manually pushed the mtgo tournaments while I investigate this issue.

**Comment by Badaro** [comment]
Temporarily disabling to resume mtgo scraping while I investigate the issue. Discussion for that will be done on #49.

**Comment by Badaro** [comment]
Moving the melee discussion to a more proper location: https://github.com/Badaro/MTGODecklistCache.Tools/issues/11
